-- MySQL Script generated by MySQL Workbench
-- Sat May  7 13:26:02 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookmarx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookmarx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookmarx` DEFAULT CHARACTER SET utf8 ;
USE `bookmarx` ;

-- -----------------------------------------------------
-- Table `bookmarx`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`accounts` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`folders` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `deleted ` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`account_id` ASC),
  CONSTRAINT `fk_folders_accounts_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `bookmarx`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`bookmarks` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`bookmarks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `folder_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `favorite` TINYINT(1) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `deleted ` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`folder_id` ASC),
  INDEX `id_idx1` (`account_id` ASC),
  CONSTRAINT `fk_bookmarks_folders_id`
    FOREIGN KEY (`folder_id`)
    REFERENCES `bookmarx`.`folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookmarks_accounts_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `bookmarx`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`keywords` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `bookmark_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`bookmark_id` ASC),
  INDEX `id_idx1` (`account_id` ASC),
  CONSTRAINT `fk_keywords_bookmarks_id`
    FOREIGN KEY (`bookmark_id`)
    REFERENCES `bookmarx`.`bookmarks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keywords_accounts_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `bookmarx`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
