-- MySQL Script generated by MySQL Workbench
-- Sat May  7 11:13:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookmarx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookmarx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookmarx` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- This schema was created for a stub table

-- -----------------------------------------------------
-- Schema mydb
--
-- This schema was created for a stub table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `bookmarx` ;

-- -----------------------------------------------------
-- Table `bookmarx`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`keywords` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `bookmark_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`bookmarks` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`bookmarks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `folder_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `favorite` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `bookmark_id`
    FOREIGN KEY ()
    REFERENCES `bookmarx`.`keywords` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`folders` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `folder_id`
    FOREIGN KEY (`id`)
    REFERENCES `bookmarx`.`bookmarks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmarx`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmarx`.`accounts` ;

CREATE TABLE IF NOT EXISTS `bookmarx`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NULL,
  INDEX `account_id_idx` (`id` ASC),
  CONSTRAINT `account_id`
    FOREIGN KEY (`id`)
    REFERENCES `bookmarx`.`bookmarks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY (`id`)
    REFERENCES `bookmarx`.`folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY (`id`)
    REFERENCES `bookmarx`.`keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bookmarx` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
