module.exports = {
  ECRYPT_KEY: "aes-256-ctr",
  ENCRYPT_PASS: "OMG_SUCH_DOGE_666_777",
  SESSION_KEY: 'OMG_NODE_SESSIONc00l',
  DATABASE_HOST: '54.218.36.167',
  DATABASE_USER: 'root',
  DATABASE_PASSWORD: 'QZsaTh3M',
  DATABASE_NAME: 'books',
  PORT: 5001
};
