module.exports = {
  ECRYPT_KEY: "aes-256-ctr",
  ENCRYPT_PASS: "OMG_SUCH_DOGE_666_777",
  SESSION_KEY: 'OMG_NODE_SESSIONc00l',
  DATABASE_HOST: 'localhost',
  DATABASE_USER: 'root',
  DATABASE_PASSWORD: '88619463',
  DATABASE_NAME: 'bookmarx',
  PORT: 5001
};
