module.exports = {
  ECRYPT_KEY: "aes-256-ctr",
  ENCRYPT_PASS: "OMG_SUCH_DOGE_666_777",
  SESSION_KEY: 'OMG_NODE_SESSIONc00l',
  DATABASE_HOST: '',
  DATABASE_USER: '',
  DATABASE_PASSWORD: '',
  DATABASE_NAME: '',
  PORT: 5001
};
